-- MySQL Script generated by MySQL Workbench
-- Thu Mar  6 11:40:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------
-- DROP DATABASE `cinema`;
CREATE SCHEMA IF NOT EXISTS `cinema` DEFAULT CHARACTER SET utf16 COLLATE utf16_czech_ci ;
USE `cinema` ;

-- -----------------------------------------------------
-- Table `cinema`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_czech_ci;


-- -----------------------------------------------------
-- Table `cinema`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(50) NOT NULL,
  `lastName` VARCHAR(50) NOT NULL,
  `email` VARCHAR(320) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `FK_role` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_role1_idx` (`FK_role` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_czech_ci;


-- -----------------------------------------------------
-- Table `cinema`.`hall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`hall` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_czech_ci;


-- -----------------------------------------------------
-- Table `cinema`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`genre` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_czech_ci;


-- -----------------------------------------------------
-- Table `cinema`.`film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`film` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `length` INT UNSIGNED NOT NULL,
  `releaseDate` DATE NOT NULL,
  `description` LONGTEXT NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `FK_genre` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_film_genre_idx` (`FK_genre` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_czech_ci;


-- -----------------------------------------------------
-- Table `cinema`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`language` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `language` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_czech_ci;


-- -----------------------------------------------------
-- Table `cinema`.`film_has_dubbing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`film_has_dubbing` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FK_film` INT UNSIGNED NOT NULL,
  `language_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_film_has_language_film1_idx` (`FK_film` ASC) VISIBLE,
  INDEX `fk_film_has_dubbing_language1_idx` (`language_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_czech_ci;


-- -----------------------------------------------------
-- Table `cinema`.`film_has_subtitles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`film_has_subtitles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FK_film` INT UNSIGNED NOT NULL,
  `FK_language` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_film_has_language_language1_idx` (`FK_language` ASC) VISIBLE,
  INDEX `fk_film_has_language_film2_idx` (`FK_film` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_czech_ci;


-- -----------------------------------------------------
-- Table `cinema`.`film_screening`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`film_screening` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dateTime` DATETIME NOT NULL,
  `FK_hall` INT UNSIGNED NOT NULL,
  `FK_film` INT UNSIGNED NOT NULL,
  `FK_film_has_dubbing` INT UNSIGNED NOT NULL,
  `FK_film_has_subtitles` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `FK_hall` (`dateTime` ASC) VISIBLE,
  INDEX `fk_film_screening_hall1_idx` (`FK_hall` ASC) VISIBLE,
  INDEX `fk_film_screening_film1_idx` (`FK_film` ASC) VISIBLE,
  INDEX `fk_film_screening_film_has_dubbing1_idx` (`FK_film_has_dubbing` ASC) VISIBLE,
  INDEX `fk_film_screening_film_has_subtitles1_idx` (`FK_film_has_subtitles` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_czech_ci;


-- -----------------------------------------------------
-- Table `cinema`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`booking` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FK_user` INT UNSIGNED NOT NULL,
  `FK_screening` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_booking_user1_idx` (`FK_user` ASC) VISIBLE,
  INDEX `fk_booking_film_screening1_idx` (`FK_screening` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_czech_ci;


-- -----------------------------------------------------
-- Table `cinema`.`seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`seat` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `seatNumber` INT UNSIGNED NOT NULL,
  `rowNumber` INT UNSIGNED NOT NULL,
  `FK_hall` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `seatNumber` (`seatNumber` ASC, `rowNumber` ASC) VISIBLE,
  INDEX `fk_seat_hall1_idx` (`FK_hall` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_czech_ci;


-- -----------------------------------------------------
-- Table `cinema`.`booking_has_seat1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`booking_has_seat1` (
  `FK_booking` INT UNSIGNED NOT NULL,
  `FK_seat` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`FK_booking`, `FK_seat`),
  INDEX `fk_booking_has_seat1_seat1_idx` (`FK_seat` ASC) VISIBLE,
  INDEX `fk_booking_has_seat1_booking1_idx` (`FK_booking` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_czech_ci;


-- -----------------------------------------------------
-- Table `cinema`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`review` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` LONGTEXT NOT NULL,
  `stars` TINYINT(1) NOT NULL,
  `FK_user` INT UNSIGNED NOT NULL,
  `FK_film` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_review_user1_idx` (`FK_user` ASC) VISIBLE,
  INDEX `fk_review_film1_idx` (`FK_film` ASC) VISIBLE,
  CONSTRAINT `fk_review_user1`
    FOREIGN KEY (`FK_user`)
    REFERENCES `cinema`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_film1`
    FOREIGN KEY (`FK_film`)
    REFERENCES `cinema`.`film` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
